a = input('Digite Algo: ')
print('O tipo primitivo desse valor é ',type(a))
print('So tem espaços ?', a.isspace())
print('É um numero ?', a.isnumeric())
print('È alfabetico ?', a.isalpha())
print('É alfanumerico ?', a.isalnum())
print('Esta em maisculas ?', a.isupper())
print('Esta em minusculas ?', a.islower())
print('Esta capitalizada ?', a.istitle())
